### ISSUE TITLE
从cn 0.63升级到0.64之后，无法读取之前0.63的会话

### ISSUE THREAD

**Issue by nsb2006** [larryli/PuTTY#1]
之前也是中文版免安装的，0.63，替换为0.64之后保存的会话列表只有默认设置，换回0.63正常。
请问可以导入0.64吗，谢谢。

**Comment by larryli** [comment]
没有问题啊。请确认。

PuTTY 0.63 可以读到两个注册表项目。
![putty-0 63cn3](https://cloud.githubusercontent.com/assets/10723/7646381/30bba16e-faf5-11e4-966a-248a3ddad611.jpg)

PuTTY 0.64 也可以读到。
![putty-0 64cn](https://cloud.githubusercontent.com/assets/10723/7646389/4c7703bc-faf5-11e4-9d64-ca9b83a04629.jpg)

PuTTYFile 0.63 多了两个本地项目。
![puttyfile-0 63cn3](https://cloud.githubusercontent.com/assets/10723/7646394/5e9d6f18-faf5-11e4-86f8-db14daf89fc9.jpg)

Portable PuTTY 0.64 也可以读到。
![portable-putty-0 64cn](https://cloud.githubusercontent.com/assets/10723/7646368/025136f4-faf5-11e4-882c-da885812785d.jpg)

请确定 PuTTY 和 PuTTYFile/Portable PuTTY 是两个不同的发布。

**Comment by larryli** [comment]
如果之前的版本是用的 PuTTYFile 请升级为[便携 PuTTY 0.64 中文版](https://github.com/larryli/PuTTY/releases/tag/portable-putty-0.64cn)

**Comment by nsb2006** [comment]
啊啊，搞错了以前的0.63版本是在你的google code上下载的，看到0.64以为只有便携版，原来有两个版本，下载便携版后正常。
感谢。

**Comment by nsb2006** [comment]
建议在项目首页分别给出两个版本的下载地址，到tag里找有点麻烦。
