### ISSUE TITLE
0.67 遭 Windows Defender 隔离

### ISSUE THREAD

**Issue by h404bi** [larryli/PuTTY#12]
Windows 10 1067

WIndows Defender:

```
反恶意软件客户端版本: 4.10.14393.0
引擎版本: 1.1.13103.0
防病毒定义: 1.229.52.0
反间谍软件定义: 1.229.52.0
网络检查系统引擎版本: 2.1.12706.0
网络检查系统定义版本: 116.26.0.0
```

portable-putty-0.67cn.zip（【推荐】便携 PuTTY 0.67 中文版）中除了 `pageant.exe` & `puttytel.exe` 外全部被 Windows Defender 隔离。

0.64 版（portable-putty-0.64cn.zip）倒没这个问题。

来反馈一下，嗯。

**Comment by larryli** [comment]
建议自行编译查一下。

**Comment by larryli** [comment]
[jakub@kotrla.net](http://jakub.kotrla.net/putty/) 确定了具体的问题（是 2016 年 11 月 6 日，不是 6 月 11 日）：
6. 11. 2016 - recompiled in debug mode to avoid false positives of overcautious Antivirus SW

近期会更新。

**Comment by larryli** [comment]
Windows 10 1067

WIndows Defender:
> 反恶意软件客户端版本: 4.10.14393.0
> 引擎版本: 1.1.13303.0
> 防病毒定义: 1.233.370.0
> 反间谍软件定义: 1.233.370.0
> 网络检查系统引擎版本: 2.1.12706.0
> 网络检查系统定义版本: 116.67.0.0

现在没报毒。请确认。

如果没问题，就不发布 debug 版本了。直接关闭此 issue。

**Comment by h404bi** [comment]
情况依旧，不过这次 `putty.exe` 与 `puttygen.exe` 不再报毒了。
![image](https://cloud.githubusercontent.com/assets/5764917/20564348/da2cfbc8-b1c7-11e6-862a-cce161342d4f.png)

```
反恶意软件客户端版本: 4.10.14393.0
引擎版本: 1.1.13303.0
防病毒定义: 1.233.412.0
反间谍软件定义: 1.233.412.0
网络检查系统引擎版本: 2.1.12706.0
网络检查系统定义版本: 116.67.0.0
```

**Comment by larryli** [comment]
1.233.474.0 扫描完全没问题啊，奇怪。
