### ISSUE TITLE
PuTTY released 0.68 on 2017-02-21

### ISSUE THREAD

**Issue by ejzhang** [larryli/PuTTY#13]
http://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

**Comment by shui0855** [comment]
http://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html

**Comment by larryli** [comment]
始终没搞定 VS 2010 Express 下 x64 编译，只好[注释掉相关代码](https://github.com/larryli/PuTTY/pull/14/commits/bbbf65212e1f130d74e9921e0f120bd1217aa626#diff-1627c4165cee0f16c842d5e2f93c028a)。
没有问题的话，本周会释出 RC 版本。

**Comment by larryli** [comment]
发布 [PuTTY 0.68 中文预览版](https://github.com/larryli/PuTTY/releases/tag/putty-0.68cn-rc)

**Comment by larryli** [comment]
明天应该会更新便携版本的 rc。
