### ISSUE TITLE
请求更新

### ISSUE THREAD

**Issue by wuhang2003** [larryli/PuTTY#19]
官网已更新到0.70，请求更新
 2017-07-08 PuTTY 0.70 released, containing security and bug fixes

PuTTY 0.70, released today, fixes further problems with Windows DLL hijacking, and also fixes a small number of bugs in 0.69, including broken printing support and Unicode keyboard input on Windows.

**Comment by larryli** [comment]
https://github.com/larryli/PuTTY/releases/tag/putty-0.70cn
