### ISSUE TITLE
Makefile not found

### ISSUE THREAD

**Issue by saurabhverma999** [larryli/PuTTY#24]
When i run this " windows/Makefile.mgw is for MinGW / Cygwin installations. Type `make -f Makefile.mgw' while in the `windows' subdirectory to build all the PuTTY binaries."

make: Makefile.mgw: No such file or directory

**Comment by larryli** [comment]
Please get makefile from https://the.earth.li/~sgtatham/putty/latest/putty-0.70.tar.gz
