### ISSUE TITLE
NMAKE : fatal error dont know how to make 

### ISSUE THREAD

**Issue by saurabhverma999** [larryli/PuTTY#25]
When i try to make this using Visual Studio command prompt it gives the following error 

NMAKE : fatal error  U1073 dont know how to make '..\licence.h'

**Comment by larryli** [comment]
Run [licence.pl](licence.pl) in shell.

**Comment by saurabhverma999** [comment]
It worked properly.
Just 1 thing, it asks for empty.h which is not provided over here.

i downloaded it from https://the.earth.li/~sgtatham/putty/latest/putty-0.70.tar.gz
