### ISSUE TITLE
0.71已更新

### ISSUE THREAD

**Issue by withero** [larryli/PuTTY#29]
你好，官网新版已经更新，麻烦跟进。谢谢

**Comment by songchaoyuan** [comment]
是啊,能否跟进下啊

**Comment by hr157** [comment]
THX，please without delay follow-up CN version！

**Comment by larryli** [comment]
不等 http://jakub.kotrla.net/putty/ 更新了，计划排在下周（4/15-4/21）更新。

**Comment by wanyanjiabin** [comment]
http://jakub.kotrla.net/putty/ 已经更新了0.71
