### ISSUE TITLE
PuTTY for win32 storing configuration into file 有更新了，可以同步更新一下吗

### ISSUE THREAD

**Issue by jazzly** [larryli/PuTTY#3]
27. 9. 2015 - Update: this modified PuTTY is now based on PuTTY 0.65 (version 0.8)
27. 9. 2015 - Update: this modified PuTTY is now based on PuTTY Development snapshot 2015-09-27.acff0a6 to provide some new ciphers e.g. ed25519 curves and chacha20. (version 0.8.1)

**Comment by larryli** [comment]
http://jakub.kotrla.net/putty/winpgnt.c
0.8.1 from 27. 9. 2015

这个版本没法编译通过

```c
#include "pageant.h"
```

这个头文件不存在，然后一系列的未定义。

**Comment by larryli** [comment]
27. 9. 2015 - Update: this modified PuTTY is now based on PuTTY Development snapshot 2015-09-27.acff0a6 to provide some new ciphers e.g. ed25519 curves and chacha20. (version 0.8.1)

当前的补丁是针对开发版，也就是 master 分支的。。。
