### ISSUE TITLE
18. 11. 2015 - Update: this modified PuTTY is now based on PuTTY 0.66 (version 0.9)

### ISSUE THREAD

**Issue by iceppu** [larryli/PuTTY#5]
18. 11. 2015 - Update: this modified PuTTY is now based on PuTTY 0.66 (version 0.9)
6. 12. 2015 - Update: this modified PuTTY is now based on PuTTY Development snapshot 2015-11-30.1659cf3 to provide some new ciphers e.g. ed25519 curves and chacha20. (version 0.9.1)

**Comment by larryli** [comment]
merge to #11 
跳过 0.66 版
