### ISSUE TITLE
你好LARRYLI

### ISSUE THREAD

**Issue by linovo** [larryli/PuTTY#6]
这个版本，现在读取会话列表不是读取根目录的session目录里边的了吗？我现在用的你之前编译的0.63cn 是有这个功能的，但是新版的下载下来没有这个功能哦。

**Comment by larryli** [comment]
文件版没更新。

**Comment by GeorKwan** [comment]
现在的putty是否支持ecdsa密钥对了？

**Comment by larryli** [comment]
merge to #11
