### ISSUE TITLE
win10下载乱码

### ISSUE THREAD

**Issue by ZAIDU-Miren** [larryli/PuTTY#64]
作者你好，辛苦看看怎么回事
![image](https://github.com/larryli/PuTTY/assets/92215296/a533328f-6d0c-473e-aaf1-770af9a3d82e)

**Comment by larryli** [comment]
目前版本 Windows 11 下增加清单配置可以解决乱码问题。Windows 10 不支持该特性。

**Comment by larryli** [comment]
[putty-x64-0.80-cn2.zip](https://github.com/larryli/PuTTY/files/14916761/putty-x64-0.80-cn2.zip)
UTF-8 测试版本，仅支持 Windows 10/11 64 位系统。

**Comment by larryli** [comment]
> [putty-x64-0.80-cn2.zip](https://github.com/larryli/PuTTY/files/14916761/putty-x64-0.80-cn2.zip) UTF-8 测试版本，仅支持 Windows 10/11 64 位系统。

此版本 pageant 任务栏菜单选择中文名称的会话，无法正确调用 putty。

**Comment by larryli** [comment]
[putty-x64-0.80-cn2-p1.zip](https://github.com/larryli/PuTTY/files/14930472/putty-x64-0.80-cn2-p1.zip)
新的测试版本，修正了 pageant 调用中文名称会话。

**Comment by larryli** [comment]
已发布 [UTF-8 版本](https://github.com/larryli/PuTTY/releases/tag/0.81-cn2)供测试。
