### ISSUE TITLE
360报毒： 木马(HEUR/QVM10.1.E064.Malware.Gen)

### ISSUE THREAD

**Issue by whatcq** [larryli/PuTTY#9]
360报毒：
putty-0.66cn.zip
木马(HEUR/QVM10.1.E064.Malware.Gen)

**Comment by larryli** [comment]
https://www.virustotal.com/zh-cn/url/17231e27ebde80eb64dedb6cd535689c5653c99aef807b61bd47c6c0d518ef2e/analysis/1461759167/
